export * from "./activation-events.js";
export * from "./contributions.js";
export * from "./dependencies.js";
export * from "./ids.js";
export * from "./lifecycle.js";
export * from "./manifest-json-schema.js";
export * from "./manifest.js";
export * from "./permissions.js";
export * from "./versioning.js";
