import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { DiscoveredAccount, ManagedAccount, UsageBreakdown, UsageDailyPoint, UsageForecast, UsageRange, UsageWindow } from "@workbench/contracts";
import { Activity, AlertTriangle, BarChart3, Clock3, Coins, Database, Edit3, KeyRound, Plus, RefreshCw, Trash2, UserRound, X } from "lucide-react";
import { useMemo, useState } from "react";
import { QueryBoundary } from "../components/QueryBoundary";
import { WebTerminal } from "../components/terminal/WebTerminal";
import { Badge } from "../components/primitives";
import { apiClient } from "../lib/apiClient";
import { formatRelativeTime } from "../lib/format";
import { workbenchQueries } from "../lib/queryOptions";

type Tab = "overview"|"history"|"breakdown"|"accounts";
const tabs: Array<{id:Tab;label:string}> = [{id:"overview",label:"Übersicht"},{id:"history",label:"Verlauf"},{id:"breakdown",label:"Projekte & Modelle"},{id:"accounts",label:"Accounts"}];
const ranges: UsageRange[] = ["7d","30d","90d","365d"];
const number = new Intl.NumberFormat("de-DE", { notation: "compact", maximumFractionDigits: 1 });
const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "USD", maximumFractionDigits: 2 });

function windowLabel(window: UsageWindow): string {
  return window.windowMinutes === 43_200 ? "Monatslimit" : window.label;
}

function WindowCard({window}:{window:UsageWindow}) {
  return <article className="usage-window"><div className="usage-window-heading"><div><p className="usage-window-label">{windowLabel(window)}</p><div className="usage-window-reset"><Clock3 className="h-3.5 w-3.5"/><span>{window.resetsAt ? `Reset ${new Date(window.resetsAt).toLocaleString("de-DE",{dateStyle:"short",timeStyle:"short"})}` : "Resetzeit nicht verfügbar"}</span></div></div><div className="usage-window-value"><strong>{window.remainingPercent}%</strong><span>verbleibend</span></div></div><div className="usage-meter" role="progressbar" aria-valuenow={window.usedPercent} aria-valuemin={0} aria-valuemax={100}><span className="usage-meter-fill" style={{width:`${window.usedPercent}%`}}/></div><p className="usage-window-used">{window.usedPercent}% verbraucht</p></article>;
}

function ForecastCard({ forecast }: { forecast: UsageForecast }) {
  const provider = forecast.providerId === "codex" ? "Codex" : "OpenCode Go";
  const projection = forecast.reachesLimitAt
    ? `Limit voraussichtlich ${new Date(forecast.reachesLimitAt).toLocaleString("de-DE", { dateStyle: "short", timeStyle: "short" })}`
    : `${Math.round(Math.min(100, forecast.predictedUsedPercentAtReset))}% Verbrauch zum Reset`;
  return <article><Clock3/><div><strong>{provider} · {forecast.accountLabel} · {forecast.windowLabel}</strong><p>{forecast.message}</p><small>{projection} · Reset {new Date(forecast.resetsAt).toLocaleString("de-DE", { dateStyle: "short", timeStyle: "short" })} · {forecast.sampleCount} Messpunkte · Konfidenz {forecast.confidence}</small></div></article>;
}

function TokenChart({data}:{data:UsageDailyPoint[]}) {
  const width=900,height=260,pad=34,max=Math.max(1,...data.map((d)=>d.totalTokens));
  if (!data.length) return <p className="usage-empty">Für diesen Zeitraum liegen noch keine Tokenwerte vor.</p>;
  return <div className="usage-chart-scroll"><svg className="usage-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Tokenverbrauch nach Tag"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/>{data.map((d,i)=>{const slot=(width-pad*2)/data.length;const bar=Math.max(3,slot*.62);const x=pad+i*slot+(slot-bar)/2;const totalHeight=d.totalTokens/max*(height-pad*2);const outputHeight=d.outputTokens/max*(height-pad*2);return <g key={d.date}><rect className="usage-chart-bar" x={x} y={height-pad-totalHeight} width={bar} height={totalHeight}><title>{`${d.date}: ${number.format(d.totalTokens)} Tokens, ${money.format(d.totalCost)}`}</title></rect><rect className="usage-chart-output" x={x} y={height-pad-outputHeight} width={bar} height={outputHeight}/>{(i===0||i===data.length-1||i%Math.ceil(data.length/6)===0)&&<text x={x+bar/2} y={height-10} textAnchor="middle">{d.date.slice(5)}</text>}</g>})}</svg></div>;
}

function Breakdown({title,items}:{title:string;items:UsageBreakdown[]}) {
  const max=Math.max(1,...items.map((item)=>item.totalTokens));
  return <section className="usage-breakdown"><h2>{title}</h2>{items.length?items.slice(0,12).map((item)=><div className="usage-rank" key={item.id}><div className="usage-rank-head"><span>{item.label}</span><strong>{number.format(item.totalTokens)}</strong></div><div className="usage-rank-track"><span style={{width:`${item.totalTokens/max*100}%`}}/></div><small>{money.format(item.totalCost)} · {item.quality==="exact"?"exakt":item.quality==="derived"?"abgeleitet":"nicht zugeordnet"}</small></div>):<p className="usage-empty">Noch keine aufgeschlüsselten Daten verfügbar.</p>}</section>;
}

function AccountManager() {
  const client=useQueryClient(); const accounts=useQuery(workbenchQueries.accounts()); const discovered=useQuery(workbenchQueries.discoveredAccounts());
  const [provider,setProvider]=useState<"codex"|"opencode">("codex"); const [label,setLabel]=useState(""); const [path,setPath]=useState(""); const [login,setLogin]=useState<ManagedAccount|null>(null); const [notice,setNotice]=useState<string|null>(null);
  const refresh=()=>void Promise.all([client.invalidateQueries({queryKey:["accounts"]}),client.invalidateQueries({queryKey:["usage"]})]);
  const create=useMutation({mutationFn:()=>apiClient.createAccount({provider,label,profilePath:path||undefined,source:"local"}),onSuccess:()=>{setLabel("");setPath("");setNotice("Das lokale Profil wurde registriert.");refresh();},onError:(error)=>setNotice(error instanceof Error?error.message:"Account konnte nicht hinzugefügt werden.")});
  const register=useMutation({mutationFn:(item:DiscoveredAccount)=>apiClient.createAccount({provider:item.provider,label:item.label,profilePath:item.profilePath,source:"local"}),onSuccess:()=>{setNotice("Das gefundene Profil wurde registriert.");refresh();},onError:(error)=>setNotice(error instanceof Error?error.message:"Profil konnte nicht registriert werden.")});
  const startLogin=useMutation({mutationFn:()=>apiClient.startLogin({provider,label}),onSuccess:(value)=>{if(value?.account)setLogin(value.account);setNotice(null);refresh();},onError:(error)=>setNotice(error instanceof Error?error.message:"Anmeldung konnte nicht gestartet werden.")});
  const update=useMutation({mutationFn:({id,body}:{id:string;body:{label?:string;enabled?:boolean}})=>apiClient.updateAccount(id,body),onSuccess:()=>{setNotice("Account wurde aktualisiert.");refresh();},onError:(error)=>setNotice(error instanceof Error?error.message:"Account konnte nicht aktualisiert werden.")});
  const remove=useMutation({mutationFn:(account:ManagedAccount)=>apiClient.deleteAccount(account.id),onSuccess:(_value,account)=>{if(login?.id===account.id)setLogin(null);setNotice(`${account.label} wurde aus Workbench und CodexBar entfernt. Das lokale Profil bleibt erhalten.`);refresh();},onError:(error)=>setNotice(error instanceof Error?error.message:"Account konnte nicht entfernt werden.")});
  const closeLogin=()=>{setLogin(null);void apiClient.syncUsage().catch(()=>undefined).finally(refresh);};
  const accountById=new Map(accounts.data?.accounts.map((account)=>[account.id,account])??[]);
  return <div className="account-manager">
    <section className="account-add-card"><div><p className="usage-provider-kicker">Hinzufügen</p><h2>Account verbinden</h2><p>Codex verwendet auf diesem Server immer die Remote-Anmeldung per Gerätecode. Anmeldedaten bleiben ausschließlich im ausgewählten lokalen CLI-Profil.</p></div><div className="account-form"><label>Werkzeug<select value={provider} onChange={(e)=>setProvider(e.target.value as typeof provider)}><option value="codex">Codex</option><option value="opencode">OpenCode</option></select></label><label>Anzeigename<input value={label} onChange={(e)=>setLabel(e.target.value)} placeholder="Privat, Arbeit …"/></label><label className="account-path">Vorhandener Profilpfad<input value={path} onChange={(e)=>setPath(e.target.value)} placeholder="Optional für lokales Profil"/></label><div className="account-form-actions"><button className="quiet-button" disabled={!label||!path||create.isPending} onClick={()=>create.mutate()}><Plus className="h-4 w-4"/>Profil registrieren</button><button className="quiet-button-primary" disabled={!label||startLogin.isPending} onClick={()=>startLogin.mutate()}><KeyRound className="h-4 w-4"/>{provider==="codex"?"Mit Gerätecode anmelden":"Neu anmelden"}</button></div></div>{notice?<div className="usage-alert" role="status"><AlertTriangle className="h-4 w-4"/>{notice}</div>:null}</section>
    <section className="account-discovery"><div className="usage-section-heading"><div><p className="usage-provider-kicker">Accounts</p><h2>Profile und Verwaltung</h2><p>Gefundene lokale Profile und registrierte Accounts werden hier gemeinsam verwaltet.</p></div><button className="quiet-button" onClick={()=>void discovered.refetch()}><RefreshCw className="h-4 w-4"/>Neu suchen</button></div><div className="managed-account-grid">{discovered.data?.accounts.map((item)=>{const account=item.accountId?accountById.get(item.accountId):undefined;return <article className="managed-account" key={`${item.provider}:${item.profilePath}`}><header><div className="managed-account-icon"><UserRound className="h-5 w-5"/></div><div><strong>{item.label}</strong><small>{item.provider==="codex"?"Codex":"OpenCode"} · {item.registered?(item.source==="login"?"Workbench-Profil":"Lokales Profil"):"gefunden"}</small></div><div className="managed-account-badges"><Badge tone={item.authenticated?"ok":"warn"}>{item.authenticated?"angemeldet":"Anmeldung fehlt"}</Badge>{item.registered?<Badge tone={item.enabled?"ok":"warn"}>{item.enabled?"aktiv":"inaktiv"}</Badge>:null}</div></header><code title={item.profilePath}>{item.profilePath}</code>{account?<div className="managed-account-actions"><button className="icon-button" aria-label={`${account.label} umbenennen`} onClick={()=>{const next=window.prompt("Neuer Anzeigename",account.label);if(next?.trim())update.mutate({id:account.id,body:{label:next.trim()}})}}><Edit3 className="h-4 w-4"/></button><button className="quiet-button" onClick={()=>setLogin(account)}><KeyRound className="h-4 w-4"/>{account.provider==="codex"?"Geräte-Anmeldung":"Anmelden"}</button><button className="quiet-button" onClick={()=>update.mutate({id:account.id,body:{enabled:!account.enabled}})}>{account.enabled?"Deaktivieren":"Aktivieren"}</button><button className="quiet-button account-remove-button" disabled={remove.isPending} onClick={()=>{if(window.confirm(`${account.label} aus Workbench und CodexBar entfernen? Das lokale Profil und seine Anmeldedaten bleiben erhalten.`))remove.mutate(account)}}><Trash2 className="h-4 w-4"/>Entfernen</button></div>:<div className="managed-account-actions"><button className="quiet-button" disabled={register.isPending} onClick={()=>register.mutate(item)}><Plus className="h-4 w-4"/>Registrieren</button></div>}</article>})}</div></section>
    {login?<div className="account-login-overlay" role="dialog" aria-modal="true" aria-label={`${login.label} anmelden`}><div className="account-login-sheet"><header><div><p className="usage-provider-kicker">Remote CLI-Anmeldung</p><h2>{login.label}</h2></div><button className="icon-button" onClick={closeLogin} aria-label="Anmeldung schließen"><X className="h-5 w-5"/></button></header><p>{login.provider==="codex"?"Kopiere den einmaligen Code aus dem Terminal und öffne die dort genannte Adresse auf deinem eigenen Gerät. Die Anmeldung benötigt keinen localhost-Rückruf auf diesem Server.":"Folge den Anweisungen im Terminal. Nach dem Schließen werden Status und Limits neu geladen."}</p><div className="account-login-terminal"><WebTerminal instanceId={`login-device-v1-${login.id}`} kind={login.provider} mode="login" accountId={login.id}/></div></div></div>:null}
  </div>;
}

export function Usage() {
  const [tab,setTab]=useState<Tab>("overview"); const [range,setRange]=useState<UsageRange>("30d"); const client=useQueryClient();
  const query=useQuery(workbenchQueries.usageDashboard(range)); const sync=useMutation({mutationFn:()=>apiClient.syncUsage(),onSuccess:()=>void client.invalidateQueries({queryKey:["usage"]})});
  const activeDays=useMemo(()=>query.data?.daily.filter((d)=>d.totalTokens>0).length??0,[query.data]);
  return <div className="page-scroll"><div className="page-frame usage-page"><header className="usage-hero"><p className="usage-eyebrow">Lokale Nutzungsanalyse</p><h1>Nutzung und Limits</h1><p>Tokens, Kosten, Projekte und Limits aus CodexBar – historisch gespeichert und mit nachvollziehbaren Prognosen.</p></header><nav className="usage-tabs" aria-label="Nutzungsbereiche">{tabs.map((item)=><button className={tab===item.id?"is-active":""} key={item.id} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav>
  {tab!=="accounts"?<QueryBoundary {...query} loadingLabel="Statistiken werden geladen…">{(data)=><><section className="usage-toolbar"><div><Database className="h-4 w-4"/><span>{data.live.lastSuccessfulFetchAt?`Datenstand ${formatRelativeTime(data.live.lastSuccessfulFetchAt)}`:"Noch kein erfolgreicher Abruf"}</span></div><div className="usage-range">{ranges.map((item)=><button className={range===item?"is-active":""} key={item} onClick={()=>setRange(item)}>{item.replace("d"," T")}</button>)}</div><button className="quiet-button" disabled={sync.isPending} onClick={()=>sync.mutate()}><RefreshCw className={`h-4 w-4 ${sync.isPending?"animate-spin":""}`}/>Synchronisieren</button></section>
  {tab==="overview"?<><section className="usage-kpis"><article><Activity/><span>Tokens heute</span><strong>{number.format(data.totals.todayTokens)}</strong></article><article><Database/><span>Tokens im Zeitraum</span><strong>{number.format(data.totals.totalTokens)}</strong></article><article><Coins/><span>Kosten im Zeitraum</span><strong>{money.format(data.totals.totalCost)}</strong></article><article><BarChart3/><span>Aktive Tage</span><strong>{activeDays}</strong></article></section><div className="usage-providers">{data.live.providers.map((provider)=><section className="usage-provider" key={provider.providerId}><header className="usage-provider-heading"><div><p className="usage-provider-kicker">{provider.status}</p><h2 className="usage-provider-title">{provider.providerName}</h2></div><Badge tone={provider.status==="available"?"ok":provider.status==="partial"?"warn":"bad"}>{provider.accounts.length} Accounts</Badge></header>{provider.error?<div className="usage-alert"><AlertTriangle className="h-4 w-4"/>{provider.error.message}</div>:null}<div className="usage-accounts">{provider.accounts.map((account)=><section className="usage-account" key={account.id}><header className="usage-account-heading"><p className="usage-account-name">{account.email??account.label}</p>{account.plan?<Badge>{account.plan}</Badge>:null}</header><div className="usage-windows">{account.windows.map((window)=><WindowCard key={window.id} window={window}/>)}</div></section>)}</div></section>)}</div><section className="usage-forecast"><div className="usage-section-heading"><div><p className="usage-provider-kicker">Vorausschau</p><h2>Limitprognosen</h2></div></div>{data.forecasts.length?data.forecasts.map((forecast)=><ForecastCard key={`${forecast.providerId}-${forecast.accountId}-${forecast.windowId}`} forecast={forecast}/>):<p className="usage-empty">Mindestens drei Messpunkte desselben aktuellen Limitfensters werden für eine Prognose benötigt.</p>}</section>{Object.keys(data.resetCredits).length?<section className="usage-forecast"><div className="usage-section-heading"><div><p className="usage-provider-kicker">Codex</p><h2>Reset-Guthaben</h2></div></div>{Object.entries(data.resetCredits).flatMap(([account,credits])=>credits.map((credit)=><article key={credit.id}><Coins/><div><strong>{credit.title} · {account}</strong><p>{credit.description}</p><small>{credit.status} · gültig bis {credit.expiresAt?new Date(credit.expiresAt).toLocaleString("de-DE",{dateStyle:"medium",timeStyle:"short"}):"unbekannt"}</small></div></article>))}</section>:null}</>:null}
  {tab==="history"?<section className="usage-chart-card"><div className="usage-section-heading"><div><p className="usage-provider-kicker">Zeitreihe</p><h2>Tokens nach Tag</h2></div><div className="usage-chart-legend"><span>Gesamt</span><span>Output</span></div></div><TokenChart data={data.daily}/><div className="usage-projection"><span>30-Tage-Hochrechnung</span><strong>{number.format(data.totals.projected30DayTokens)} Tokens · {money.format(data.totals.projected30DayCost)}</strong></div></section>:null}
  {tab==="breakdown"?<div className="usage-breakdown-grid"><Breakdown title="Projekte" items={data.projects}/><Breakdown title="Modelle" items={data.models}/></div>:null}</>}</QueryBoundary>:<AccountManager/>}</div></div>;
}
